### PR TITLE
Add rogtemplate features

### PR DESCRIPTION
**Pull request by dieghernan**
Following https://github.com/orgs/rOpenGov/projects/2 and https://github.com/orgs/rOpenGov/teams/core/discussions/2

Also, site should be deployed from gh-pages branch

~Additionally, we are moving logos to an standarized format (see https://ropengov.r-universe.dev/ui#packages). Your new logo would be:~

~If you wish, I could add that to the PR as well~

### CODE REVIEW

**Comment by antaldaniel** [comment]
I do not want to do this.

**Comment by dieghernan** [comment]
I completely understand, thanks anyway to take some time on having a look

**Comment by antaldaniel** [comment]
@dieghernan My apologies, did not meant to be rude.  I sent message when you changed the website and the logo of retroharmonize that I would not like to do this with iotables, retroharmonize and regions, these are 99.9% my creations and I would like to remain in control on how they are presented.

**Comment by dieghernan** [comment]
Yes, don't worry, I understand completely, no hard feelings 😉

**Pull request closed without merging**
